### ISSUE TITLE
increasing retry times 

### ISSUE THREAD

**Issue by amitme10** [kubeflow/spark-operator#1051]
Hey @liyinan926 
Im using v1beta2-1.1.2-2.4.5 version  with those values for my streaming job :

```
  Restart Policy:
    On Failure Retries:                    1000000
    On Failure Retry Interval:             10
    On Submission Failure Retries:         1000000
    On Submission Failure Retry Interval:  10
    Type:                                  Always
```

Also I have this cronjob which delete the driver every hour - just to test how it deals with failure recovery and such.
and it works fine at the first , it takes it a few seconds to raise up again .
however after a few hours (12 h) I noticed that the raising up process isn't anymore a few seconds but a few minutes (5m), and it will keep increasing .

If I look at the operator logs Ill see the 143 error over there.

Do you know something about it ?

_Originally posted by @amitme10 in https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/issues/897#issuecomment-716449334_

**Comment by stym06** [comment]
@amitme10 Did you end up resolving this issue of delayed restarts?

**Comment by SwatGetmann** [comment]
> however after a few hours (12 h) I noticed that the raising up process isn't anymore a few seconds but a few minutes (5m), and it will keep increasing .

this is caused by `linear backoff`, that is implemented here:
https://github.com/kubeflow/spark-operator/blob/2ed985ba8ae8956f0aa1da5e9ef760694412d355/pkg/util/sparkapplication.go#L128

basically, `RetryInterval` gets multiplied by amount of retires (`attemptsDone` = `app.Status.SubmissionAttempts`)
and that explains ever increasing raise up time
