### ISSUE TITLE
volumeMounts not working in Minikube

### ISSUE THREAD

**Issue by jyyoo0530** [kubeflow/spark-operator#1179]
Hi,

volumes mounted into the minikube VM hostPath, but Pod does not mount volume from hostPath.

I guess the problem is related with CRD issue. Because, if I make sample mount with k8s object kind "Pod" with nginx image, this works fine. But if object kind goes to "CRD" it seems not working (same thing happened while applying gaffer-hdfs).

Please kindly advise if there is a way to solve the problem ?

**Comment by jgoeres** [comment]
I can say that I have been successfully using volume mounts on minikube (type hostpath) for our dev environments. 
However, for volume mounts to work at all with spark operator, you need to enable the webhook, see

https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/docs/user-guide.md#mounting-volumes

"Note that the mutating admission webhook is needed to use this feature."


When deploying the operator with Helm you can enable the webhook with "--set enableWebhook=true" on helm install.
There is also a description on how to install the operator with the webhook here (but I never tried that): 
https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/docs/quick-start-guide.md#about-the-mutating-admission-webhook

**Comment by jyyoo0530** [comment]
Thanks for your review. 

Unfortunately, I've already done with that command,

below is the linux command I use to launch spark operator.

helm install spark \
./helm/sparkoperator \
 --namespace spark-operator \
 --set webhook.enable=true,sparkJobNamespace=spark-apps,logLevel=3

below is pod status regarding spark-operator,,,,

NAMESPACE        NAME                                      READY   STATUS      RESTARTS   AGE
spark-operator   spark-spark-operator-5bb57c7c4b-zttbf     1/1     Running     0          36s
spark-operator   spark-spark-operator-webhook-init-w6ttl   0/1     Completed   0          36s

below is spark-operator logs,,,

++ id -u
+ myuid=0
++ id -g
+ mygid=0
+ set +e
++ getent passwd 0
+ uidentry=root:x:0:0:root:/root:/bin/bash
+ set -e
+ echo 0
0
0
root:x:0:0:root:/root:/bin/bash
+ echo 0
+ echo root:x:0:0:root:/root:/bin/bash
+ [[ -z root:x:0:0:root:/root:/bin/bash ]]
+ exec /usr/bin/tini -s -- /usr/bin/spark-operator -v=3 -logtostderr -namespace=spark-apps -ingress-url-format= -controller-threads=10 -resync-interval=30 -enable-batch-scheduler=false -label-selector-filter= -enable-metrics=true -metrics-labels=app_type -metrics-port=10254 -metrics-endpoint=/metrics -metrics-prefix= -enable-webhook=true -webhook-svc-namespace=spark-operator -webhook-port=8080 -webhook-svc-name=spark-spark-operator-webhook -webhook-config-name=spark-spark-operator-webhook-config -webhook-namespace-selector= -enable-resource-quota-enforcement=false
I0227 05:26:25.737257      10 main.go:143] Starting the Spark Operator
I0227 05:26:25.737427      10 main.go:176] Enabling metrics collecting and exporting to Prometheus
I0227 05:26:25.737484      10 metrics.go:142] Started Metrics server at localhost:10254/metrics
I0227 05:26:25.738732      10 webhook.go:218] Starting the Spark admission webhook server
I0227 05:26:25.744726      10 webhook.go:412] Creating a MutatingWebhookConfiguration for the Spark pod admission webhook
I0227 05:26:25.757204      10 main.go:218] Starting application controller goroutines
I0227 05:26:25.857564      10 controller.go:160] Starting the workers of the SparkApplication controller
I0227 05:26:25.857593      10 controller.go:96] Starting the ScheduledSparkApplication controller
I0227 05:26:25.857596      10 controller.go:102] Starting the workers of the ScheduledSparkApplication controller
I0227 05:28:59.729142      10 controller.go:179] SparkApplication spark-apps/kaspi-sparkjob was added, enqueueing it for submission
I0227 05:28:59.729185      10 controller.go:258] Starting processing key: "spark-apps/kaspi-sparkjob"
I0227 05:28:59.729262      10 submission.go:65] spark-submit arguments: [/opt/spark/bin/spark-submit --class kaspi.sparkjob --master k8s://https://10.96.0.1:443 --deploy-mode cluster --conf spark.kubernetes.namespace=spark-apps --conf spark.app.name=kaspi-sparkjob --conf spark.kubernetes.driver.pod.name=kaspi-sparkjob-driver --conf spark.kubernetes.container.image=localhost:5000/kaspi/kaspi-sparkjob:0.1 --conf spark.kubernetes.container.image.pullPolicy=Never --conf spark.kubernetes.submission.waitAppCompletion=false --conf spark.kubernetes.driver.label.sparkoperator.k8s.io/app-name=kaspi-sparkjob --conf spark.kubernetes.driver.label.sparkoperator.k8s.io/launched-by-spark-operator=true --conf spark.kubernetes.driver.label.sparkoperator.k8s.io/submission-id=9e63c54f-27e1-491c-86d3-c7d039417ec6 --conf spark.driver.cores=1 --conf spark.kubernetes.driver.limit.cores=1 --conf spark.driver.memory=2g --conf spark.kubernetes.authenticate.driver.serviceAccountName=spark-spark --conf spark.kubernetes.driver.label.app.kubernetes.io/managed-by=Helm --conf spark.kubernetes.driver.label.chartname=kaspi-kaspi-sparkjob --conf spark.kubernetes.driver.label.release=kaspi-sparkjob --conf spark.kubernetes.driver.label.revision=1 --conf spark.kubernetes.driver.label.sparkVersion=3.0.2 --conf spark.kubernetes.driver.label.version=0.1 --conf spark.kubernetes.executor.label.sparkoperator.k8s.io/app-name=kaspi-sparkjob --conf spark.kubernetes.executor.label.sparkoperator.k8s.io/launched-by-spark-operator=true --conf spark.kubernetes.executor.label.sparkoperator.k8s.io/submission-id=9e63c54f-27e1-491c-86d3-c7d039417ec6 --conf spark.executor.instances=3 --conf spark.executor.cores=1 --conf spark.kubernetes.executor.limit.cores=1 --conf spark.executor.memory=1g --conf spark.kubernetes.executor.label.sparkVersion=3.0.2 --conf spark.kubernetes.executor.label.version=0.1 --conf spark.kubernetes.executor.label.app.kubernetes.io/managed-by=Helm --conf spark.kubernetes.executor.label.chartname=kaspi-kaspi-sparkjob --conf spark.kubernetes.executor.label.release=kaspi-sparkjob --conf spark.kubernetes.executor.label.revision=1 local:///opt/spark/jars/kaspi-kaspi-sparkjob.jar /mnt/data-in/ /mnt/data-out/]
I0227 05:28:59.729326      10 event.go:274] Event(v1.ObjectReference{Kind:"SparkApplication", Namespace:"spark-apps", Name:"kaspi-sparkjob", UID:"1eb15a01-a3c3-41cf-9273-6520622fe5f6", APIVersion:"sparkoperator.k8s.io/v1beta2", ResourceVersion:"864", FieldPath:""}): type: 'Normal' reason: 'SparkApplicationAdded' SparkApplication kaspi-sparkjob was added, enqueuing it for submission
2021/02/27 05:29:01 http: TLS handshake error from 172.17.0.1:20840: remote error: tls: bad certificate
I0227 05:29:01.239198      10 spark_pod_eventhandler.go:47] Pod kaspi-sparkjob-driver added in namespace spark-apps.
I0227 05:29:01.247870      10 spark_pod_eventhandler.go:58] Pod kaspi-sparkjob-driver updated in namespace spark-apps.
I0227 05:29:01.260929      10 spark_pod_eventhandler.go:58] Pod kaspi-sparkjob-driver updated in namespace spark-apps.
I0227 05:29:01.490639      10 submission.go:67] spark-submit output: 
I0227 05:29:01.490651      10 controller.go:671] SparkApplication spark-apps/kaspi-sparkjob has been submitted
I0227 05:29:01.490705      10 sparkui.go:151] Creating a service kaspi-sparkjob-ui-svc for the Spark UI for application kaspi-sparkjob
I0227 05:29:01.490885      10 event.go:274] Event(v1.ObjectReference{Kind:"SparkApplication", Namespace:"spark-apps", Name:"kaspi-sparkjob", UID:"1eb15a01-a3c3-41cf-9273-6520622fe5f6", APIVersion:"sparkoperator.k8s.io/v1beta2", ResourceVersion:"864", FieldPath:""}): type: 'Normal' reason: 'SparkApplicationSubmitted' SparkApplication kaspi-sparkjob was submitted successfully
I0227 05:29:01.497390      10 controller.go:773] Update the status of SparkApplication spark-apps/kaspi-sparkjob from:
{
  "lastSubmissionAttemptTime": null,
  "terminationTime": null,
  "driverInfo": {},
  "applicationState": {
    "state": ""
  }
}
to:
{
  "submissionID": "9e63c54f-27e1-491c-86d3-c7d039417ec6",
  "lastSubmissionAttemptTime": "2021-02-27T05:29:01Z",
  "terminationTime": null,
  "driverInfo": {
    "webUIServiceName": "kaspi-sparkjob-ui-svc",
    "webUIPort": 4040,
    "webUIAddress": "10.105.75.194:4040",
    "podName": "kaspi-sparkjob-driver"
  },
  "applicationState": {
    "state": "SUBMITTED"
  },
  "executionAttempts": 1,
  "submissionAttempts": 1
}
I0227 05:29:01.502654      10 controller.go:265] Ending processing key: "spark-apps/kaspi-sparkjob"
I0227 05:29:01.502787      10 controller.go:218] SparkApplication spark-apps/kaspi-sparkjob was updated, enqueueing it
I0227 05:29:01.502812      10 controller.go:258] Starting processing key: "spark-apps/kaspi-sparkjob"
I0227 05:29:01.502913      10 controller.go:773] Update the status of SparkApplication spark-apps/kaspi-sparkjob from:

Thanks..!

**Comment by jgoeres** [comment]
Just to clarify, I am merely a user of Sparkoperator, so I can only be of limited help here. What I did notice, however, is this line in your Sparkoperator log:

    2021/02/27 05:29:01 http: TLS handshake error from 172.17.0.1:20840: remote error: tls: bad certificate

This points to the exact same problem that a number of people are reporting, see e.g.,

https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/issues/1004
https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/issues/1168

I am also observing this, but on EKS (after EKS update from 1.15 to 1.18). I tried, but couldn't reproduce it on minikube (even when using the exact same K8s version 1.18.9 that is used with EKS 1.18).

Which versions of the Sparkoperator, Minikube and Kubernetes are you using?
How are you deploying the operator? Using the YAML manifests or the Helmchart? Are you using a GitOps tool like ArgoCD?

**Comment by jgoeres** [comment]
I have been investigating the whole topic. I do not have full knowledge of what the Sparkoperator does internally, so there is a bit of guesswork in places, but for me it starts to make sense.
What seems to have broken Sparkoperator, resp. the webhook for us was our use of the Helmchart for deploying the operator.
That Helmchart comes with two jobs: the init job will run a script that creates a CA and uses that CA to produce a server key and certificate. The CA cert, CA key, server key and server cert are then put into a K8s secret, which is later mounted into the sparkoperator pod.
The server key and cert are used by the Sparkoperator's webhook endpoint for TLS (cause K8s API server will only speak with webhooks through TLS). In addition, when then the sparkoperator starts up, it will register itself as a webhook with K8s, and provides the CA cert as part of the webhook registration, so that the K8s API server trusts the cert presented by the webhook endpoint (otherwise, the K8s server will simply reject the certificate cause it is not signed by a CA that it trusts).
So far so good.
In addition to that, the Helmchart will install a cleanup job, which is run on helm upgrade and helm delete. This is done by adding a helm-specific annotation to it:

    [...]
    "helm.sh/hook": pre-delete, pre-upgrade
    [...]

So whenever you do a helm upgrade or helm delete on the sparkoperator helm release, the cleanup job will run and delete the secret with the certs and keys, and the old (completed) init job. In the case of helm upgrade, the init job is being re-run, so a new set of certs and keys is generated and put into the secret.
However, the Sparkoperator pod is NOT being restarted (from Helm's perspective, it didn't change). However, and here is where the guesswork _really_  starts, it seems that the already running Sparkoperator immediately starts using the new server cert for its TLS endpoint. However, it does not refresh the registered webhook (and the CA cert) with K8s, so the API server has the old CA cert, and thus doesn't trust the new certificate presented to it during TLS handshake.
=> Bad certificate error

Interestingly, I rarely had a reason to ever run "helm upgrade" with the Sparkoperator, so I never ran into this in my local dev environment, for which I use minikube.

However, on our cloud systems, we are using the ArgoCD Gitops tooling to install various K8s applications, including the sparkoperator, and here we are also using the same Helmchart. 
And whenever we run our GitOps pipeline, that would trigger a sync of all ArgoCD applications, including the Sparkoperator application. An ArgoCD sync is semantically similar, but not identical to a "helm upgrade". In any case, effectively the same chain of events would be triiggered, leading to a broken webhook. And since we tend to run the GitOps pipeline many times, but never noticed the cleanup job and the re-run of the init job, it took us a while to find the root cause.
And this also explains why we didn't see the problem in our previous installations - here we had not yet achieved 100% coverage of our GitOps pipeline and the Sparkoperator application had been added manually to ArgoCD. So a pipeline re-run would not affect it, no ArgoCD sync, no re-run of the cleanup and init jobs.

Our solution (or rather workaround?) is to simply remove the cleanup job from the helmchart. So the init job will never be re-run and the certificates remain stable. The only drawback I see is that since Helm didn't create the secret and the webhook itself (but the init job resp. the operator did), this will leave some residual stuff on helm delete.
However, the current set of YAML descriptors also do not seem to contain the cleanup job anymore, so we are probably fine.

Further, when playing around with this to reproduce it on minikube, I noticed that a "helm upgrade" would not always break the webhook - not sure why, I guess there is some kind of a race condition involved here, or the operator sometimes doesn't pick up the new certificate.

**Comment by jyyoo0530** [comment]
Thanks for your advice. I am approaching this issue based on related issues you mentioned.
I also have mere knowledge on kubernetes system, so that's why I am doing all this stuff in local environment(Minikube).
For my case, TLS error comes out from the first time and always, just for your reference.
Hope I can solve the matter after eliminating TLS handshake issue..!

My minikube environment is,
https://github.com/jyyoo0530/mirinae

And version of each apps are,
sparkoperator:latest
minikube: 1.17.1
kubernetes:  1.20
spark base image: 3.0.0

**Comment by brettemorris** [comment]
The MutatingWebhook simply does not work. I have tried a clean deployment (e.g. created an entirely new K8s cluster) via helm multiple times on a local minikube environment and I never see config maps or secrets set as environment variables on the driver pod. Have you even tested the helm deployment? I am trying this with minikube v1.18.1 on Darwin 11.2.3, which is running Kubernetes v1.20.2 on Docker 20.10.3. I run the following command to deploy the helm chart:

helm install spark-operator spark-operator/spark-operator --namespace spark --set webhook.enable=true,logLevel=3,sparkJobNamespace=spark,enableMetrics=true

And my operator yaml:

apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: test-pyspark
  namespace: spark
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: test-pyspark:latest
  imagePullPolicy: Never
  mainApplicationFile: local:///opt/pyspark-apps/main.py
  sparkVersion: "3.0.0"
  restartPolicy:
    type: OnFailure
    onFailureRetries: 3
    onFailureRetryInterval: 10
    onSubmissionFailureRetries: 5
    onSubmissionFailureRetryInterval: 20
  deps:
    jars:
      - local:///data/lib/postgresql-42.2.18.jar
    pyFiles:
      - local:///opt/pyspark-apps/jobs.zip
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 3.0.0
    serviceAccount: spark-operator-spark
    volumeMounts:
      - name: jars
        mountPath: "/data/lib"
    javaOptions: "-Dlog4j.configuration=file:/opt/pyspark-apps/spark_jobs/conf/log4j.properties"
    envFrom:
      - configMapRef:
          name: spark-app-config
      - secretRef:
          name: spark-app-db
  executor:
    cores: 1
    instances: 1
    memory: "512m"
    labels:
      version: "3.0.0"
    volumeMounts:
      - name: jars
        mountPath: "/data/lib"
    javaOptions: "-Dlog4j.configuration=file:/opt/pyspark-apps/spark_jobs/conf/log4j.properties"
    envFrom:
      - configMapRef:
          name: spark-app-config
      - secretRef:
          name: spark-app-db

The only way I have found to apply environment variables is to use the deprecated "envVars" option.

**Comment by jgoeres** [comment]
@brettemorris 
Did you have a look at the spark operator logs? Do yousee the "Bad certificate" error? Do you see any indications that the webhook is called? You should see log message like this whenever a new pod is created, for NON-spark pods:

    I0316 09:41:16.957742      10 webhook.go:246] Serving admission request
    I0316 09:41:16.958005      10 webhook.go:540] Pod <podname> in namespace <namespace> is not subject to mutation

For spark pods it should look like this:

    I0316 07:28:39.061448      10 webhook.go:246] Serving admission request
    I0316 07:28:39.061755      10 webhook.go:556] Pod <sparkPod> in namespace <namespace> is subject to mutation

**Comment by brettemorris** [comment]
@jgoeres I see the following in the operator logs:

I0317 13:31:22.606617      11 webhook.go:218] Starting the Spark admission webhook server
I0317 13:31:22.614446      11 webhook.go:412] Creating a MutatingWebhookConfiguration for the Spark pod admission webhook
I0317 13:31:22.619105      11 main.go:218] Starting application controller goroutines

And a little bit further down in the logs I see:

2021/03/17 13:32:46 http: TLS handshake error from 172.17.0.1:16203: remote error: tls: bad certificate

I do not, however, find "Serving admission request" anywhere in the operator logs. As I mentioned before, I've deleted my minikube cluster and started from scratch a few times and the result is always the same. Any ideas you have for getting around the problem are greatly appreciated. Thank you!

**Comment by jgoeres** [comment]
Above I describe what was causing the problems for us (init & cleanup jobs running repeatedly due to our GitOps pipeline and deficits in ArgoCD), see https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/issues/1179#issuecomment-788796683. 

Which version of Spark operator are you using? There was an issue with how the CA certificate was created (see https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/pull/1058), this issue has been patched for 3.0.0 (IIRC), we are still on 2.4.5.
This particular issue originally did not cause any noticable problems for us (IIRC, it would only become a problem on more recent Kubernetes versions). Just yesterday, we observed it on AKS 1.19. Our solution is to "port" the patch for 3.0.0 (which only affects the gencerts.sh script) to our version.

We just took the patched gencerts.sh and put it into your 2.4.5 operator image like this

    FROM <ourRegistry>/spark-operator/spark-operator:v1beta2-1.1.0-2.4.5
    ADD gencerts.sh /usr/bin/gencerts.sh
    RUN chmod +x /usr/bin/gencerts.sh

**Comment by brettemorris** [comment]
@jgoeres I am testing with latest version of the spark operator and minikube and the webhook never works. I have completely recreated my k8s cluster multiple times and retested. My colleague, however, setup the operator, without using the helm charts, in our GKE test environment and he said the webhook works there. Are you using helm to deploy the operator? I appears I will have to write my own scripts to make it easy for the development team to deploy the operator locally :(.
