### ISSUE TITLE
Failed to call webhook from API server with AWS EKS 1.19

### ISSUE THREAD

**Issue by felixng-umh** [kubeflow/spark-operator#1224]
Failed to call webhook from API server with AWS EKS 1.19

E0412 13:50:38.660172 1 dispatcher.go:171] failed calling webhook "webhook.sparkoperator.k8s.io": Post "https://spark-operator-webhook.spark-operator.svc:443/webhook?timeout=30s": x509: certificate relies on legacy Common Name field, use SANs or temporarily enable Common Name matching with GODEBUG=x509ignoreCN=0

**Comment by puneetloya** [comment]
I see a webhook problem as well, my spark configmap is not getting attached to the driver.

**Comment by jdonnelly-apixio** [comment]
I'm getting this as well after upgrading to EKS 1.19.

**Comment by jdonnelly-apixio** [comment]
I upgraded to the latest version of the spark operator and the issue was resolved.

**Comment by indranilr** [comment]
not sure if this issue is addressed already , getting the below error with AWS EKS (K8s version 1.19 and Helm v3.6.3, Operator Tag Image v1beta2-1.2.3-3.1.1 and chart version 1.1.8) , all spark applications fail to load volume, config maps,

Please note all configurations work as expected in in-premise K8 deployment.

`E1101 09:25:03.552938 1 dispatcher.go:171] failed calling webhook "webhook.sparkoperator.k8s.io": Post "https://myapp-spark-operator-webhook.myapp.svc:443/webhook?timeout=30s": Address is not allowed`

The webhook service on describing looks like below :
![image](https://user-images.githubusercontent.com/13346906/139670149-9840e65c-8268-4e5d-b028-ad5af109a37e.png)
