### ISSUE TITLE
Image for chart version 1.1.13

### ISSUE THREAD

**Issue by zzvara** [kubeflow/spark-operator#1399]
The `latest` image tag does not support `-webook-timeout` flag introduced in chart version `1.1.12`. Is the updated image available in some other place?

**Comment by echang0929** [comment]
Actually, you can build the image by yourself with the latest codes. 
```
docker build -t echang0929/spark-operator:v1beta2-1.2.3-3.1.1 .
docker push echang0929/spark-operator:v1beta2-1.2.3-3.1.1
```

You can try the one which I created and pushed temporarily: 
```bash
helm install opr-spark charts/spark-operator-chart --namespace spark-operator \
  --set sparkJobNamespace=spark-job --set webhook.enable=true \
  --set image.repository=echang0929/spark-operator --set image.tag=v1beta2-1.2.3-3.1.1
```

And validate it: 
```bash
cat examples/spark-pi.yaml | \
  sed 's/namespace: .*/namespace: spark-job/' | \
  sed 's/serviceAccount: .*/serviceAccount: opr-spark-spark/' | \
  kubectl apply -f -
```

**Comment by zzvara** [comment]
@echang0929 thanks, this was very useful!

Before I build the latest image, may I ask, what is the rationale behind not having the master branch on CD and automatic versioning, and why master has not been released so far? Is it because it is unstable or test coverage is not sufficient as of this writing?

I think at least a table should then be added to the Helm chart's README to tell users that the latest chart version depends on an image that is not yet released publicly.

**Comment by echang0929** [comment]
Hi @zzvara, very glad those codes can help you. As far as I understand it, your suggestion is very meaningful.  I think @liyinan926 can answer your questions since he is the creator and committer of this great tool. 

I notice the file .gitlab-ci.yaml. I think new docker images can be released and published automatically based on its configuration, however, probably committers need to trigger it manually, or is there any env to support it? It should be helpful if any comments about this ci file and processes can be added to the developer's document.

**Comment by TomHellier** [comment]
I've just seen [my pr was merged](https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/pull/1422), so the image should exist at [ghcr.io/googlecloudplatform/spark-operator:v1beta2-1.3.2-3.1.1](https://github.com/googlecloudplatform/spark-on-k8s-operator/pkgs/container/spark-operator)
