### ISSUE TITLE
TLS Configuration Options For Webhook

### ISSUE THREAD

**Issue by crbednarz** [kubeflow/spark-operator#1551]
Hello,

I've been looking through the documentation from the webhook and have been unable to find any options about specifying additional TLS configurations such as minimum supported version or supported ciphers.

Am I correct in my assumption that the webhook is simply using the default values out of `crypto/tls`'s `tls.Config` which would mean TLS 1.0+ and all ciphers? And is anyone aware of any mechanism for configuring the webhook TLS beyond the certificate/key?

Thanks

**Comment by RobuRishabh** [comment]
> **Note:** This issue was originally opened by @crbednarz in 2022 as a question. The answer is confirmed — there is no TLS hardening. Expanding this into a formal feature request with a proposed solution.

---

## What feature would you like to be added?

Add configurable TLS hardening for the webhook and metrics servers:
- Enforce a minimum TLS version (default `TLS 1.2`) via `--tls-min-version` flag
- Allow restricting cipher suites via `--tls-cipher-suites` flag
- Restructure `newTLSOptions()` into a `setupTLS()` function that returns a result struct, making it extensible for downstream consumers

## Why is this needed?

**1. The current code has no TLS floor**

Both `cmd/operator/webhook/start.go` and `cmd/operator/controller/start.go` define `newTLSOptions()` which only toggles HTTP/2 on/off via `NextProtos`. There is no `MinVersion`, no `CipherSuites`, no `MaxVersion`, the webhook accepts TLS 1.0 and TLS 1.1 connections with weak ciphers:

```go
func newTLSOptions() []func(c *tls.Config) {
    disableHTTP2 := func(c *tls.Config) {
        c.NextProtos = []string{"http/1.1"}
    }
    tlsOpts := []func(*tls.Config){}
    if !enableHTTP2 {
        tlsOpts = append(tlsOpts, disableHTTP2)
    }
    return tlsOpts
}
```

**2. TLS 1.0 and 1.1 are officially deprecated**

[RFC 8996](https://datatracker.ietf.org/doc/html/rfc8996) (March 2021) formally deprecated TLS 1.0 and 1.1. Compliance frameworks (PCI DSS, NIST SP 800-52r2, FedRAMP) all require TLS 1.2 as a minimum. Any operator deployed in a compliance-governed environment cannot use the Spark Operator webhook as-is without a network-layer workaround.

**3. Post-Quantum Cryptography (PQC) readiness requires cipher configurability**

As the industry migrates toward PQC-safe cipher suites ([NIST PQC standards](https://csrc.nist.gov/projects/post-quantum-cryptography)), operators need the ability to restrict cipher suites to approved ones. Without configurable ciphers, the Spark Operator becomes an obstacle in any organization's PQC migration plan.

**4. Kubernetes itself already enforces TLS 1.2+ and exposes these flags**

The kube-apiserver has `--tls-min-version` and `--tls-cipher-suites` flags. The Spark Operator webhook is the only link in the chain that doesn't enforce a floor or expose configuration — making it the weakest point in the TLS chain. Other CNCF operators (cert-manager, Argo, Istio) all set `MinVersion = tls.VersionTLS12` by default and expose cipher configuration.

## Describe the solution you would like

Replace the current `newTLSOptions()` with a structured `setupTLS()` function and add two new CLI flags. This follows the same pattern as kube-apiserver and makes the TLS configuration extensible for downstream distributions.

**New CLI flags** (both in `webhook/start.go` and `controller/start.go`):

```go
var (
    tlsMinVersion  string
    tlsCipherSuites []string
)

// In NewStartCommand():
command.Flags().StringVar(&tlsMinVersion, "tls-min-version", "VersionTLS12",
    "Minimum TLS version for the webhook and metrics servers. "+
    "Possible values: VersionTLS12, VersionTLS13")
command.Flags().StringSliceVar(&tlsCipherSuites, "tls-cipher-suites", []string{},
    "Comma-separated list of cipher suites for the webhook and metrics servers. "+
    "If omitted, the default Go cipher suites are used. "+
    "Possible values listed at https://pkg.go.dev/crypto/tls#pkg-constants")
```

**New `setupTLS()` function and result struct:**

```go
type tlsSetupResult struct {
    tlsOpts []func(*tls.Config)
}

func setupTLS() (tlsSetupResult, error) {
    var result tlsSetupResult

    // Parse and apply minimum TLS version
    minVersion, err := parseTLSVersion(tlsMinVersion)
    if err != nil {
        return result, fmt.Errorf("invalid --tls-min-version %q: %w", tlsMinVersion, err)
    }
    result.tlsOpts = append(result.tlsOpts, func(c *tls.Config) {
        c.MinVersion = minVersion
    })

    // Parse and apply cipher suites if specified
    if len(tlsCipherSuites) > 0 {
        cipherIDs, err := parseCipherSuites(tlsCipherSuites)
        if err != nil {
            return result, fmt.Errorf("invalid --tls-cipher-suites: %w", err)
        }
        result.tlsOpts = append(result.tlsOpts, func(c *tls.Config) {
            c.CipherSuites = cipherIDs
        })
    }

    // ALPN configuration based on --enable-http2 flag
    if enableHTTP2 {
        result.tlsOpts = append(result.tlsOpts, func(c *tls.Config) {
            c.NextProtos = []string{"h2", "http/1.1"}
        })
    } else {
        result.tlsOpts = append(result.tlsOpts, func(c *tls.Config) {
            c.NextProtos = []string{"http/1.1"}
        })
    }

    return result, nil
}

func parseTLSVersion(version string) (uint16, error) {
    switch version {
    case "VersionTLS12":
        return tls.VersionTLS12, nil
    case "VersionTLS13":
        return tls.VersionTLS13, nil
    default:
        return 0, fmt.Errorf("unsupported TLS version: %s (use VersionTLS12 or VersionTLS13)", version)
    }
}

func parseCipherSuites(names []string) ([]uint16, error) {
    allCiphers := make(map[string]uint16)
    for _, cs := range tls.CipherSuites() {
        allCiphers[cs.Name] = cs.ID
    }
    var ids []uint16
    for _, name := range names {
        id, ok := allCiphers[name]
        if !ok {
            return nil, fmt.Errorf("unknown cipher suite: %s", name)
        }
        ids = append(ids, id)
    }
    return ids, nil
}
```

**Updated `start()` caller:**

```go
func start() {
    setupLog()

    cfg, err := ctrl.GetConfig()
    if err != nil {
        logger.Error(err, "failed to get kube config")
        os.Exit(1)
    }

    tlsResult, err := setupTLS()
    if err != nil {
        logger.Error(err, "Failed to set up TLS")
        os.Exit(1)
    }

    mgr, err := ctrl.NewManager(cfg, ctrl.Options{
        // ...
        Metrics: metricsserver.Options{
            TLSOpts: tlsResult.tlsOpts,
        },
        WebhookServer: ctrlwebhook.NewServer(ctrlwebhook.Options{
            TLSOpts: tlsResult.tlsOpts,
        }),
        // ...
    })
    // ...
}
```
## Additional context
- The `tlsSetupResult` struct and `setupTLS()` pattern are intentionally designed to be extensible — production Kubernetes platforms often need to read TLS configuration from a central policy source (e.g., a ConfigMap, a platform API, or a cluster-wide security profile) and register watchers for live TLS policy reloads. This structure allows platform integrators to extend rather than rewrite the TLS setup, reducing fork maintenance and keeping the ecosystem aligned.


/cc @vara-bonthu @nabuskey
