### ISSUE TITLE
Can you clarify if the below scenario results into deadlock?

### ISSUE THREAD

**Issue by ravieze** [kubeflow/spark-operator#1757]
for spark on k8s with spark operator kindly tell me how it works in this case

1.     there are only 4 nodes and each with 4cores and 16gb
2.     i submit a 100 jobs each taking 1 core and 1gb ram
3.     assume 1 core 1gb per machine is given to OS. so effectively we have 3 X 4 = 12 cores

now will this scenario spin 12 drivers first? each driver wants to spin executors. but there is no room for executors. So Wouldnt all drivers wait forever? kind of deadlock. And other 88 jobs fall in queue.

Assume each driver needs 50 executors to run the program. Now what happens? 

In case of yarn on k8s,  
1. It spins only some jobs. meaning each driver will spin few executors. 
2. It doesn't wait till 50 executor JVMs are available per driver. But schedules some of the executor JVMS to the extent available on the cluster. Meaning we have parallel spark jobs running, no resources are wasted, and all of the jobs are complete. 

I expect similar behavior with spark operator on native k8s. But Need clarification. Any help?

Can you kindly let me know how this scenario behaves/ is handled?

**Comment by degant** [comment]
What you're describing is a Gang scheduling problem and we've faced the same issue. It's because Spark relies on the Kubernetes default scheduler to first run drivers, and then each driver is responsible for creating executor pods. So the k8s default scheduler doesn't understand the assocation between a driver and it's executors. Only if you could somehow _group_ them together

We're using the [Yunikorn](https://yunikorn.apache.org/) scheduler to solve this problem in our cluster. But there are a few more options out there that might work e.g. the [Volcano ](https://volcano.sh/en/docs/schduler_introduction/) scheduler

 I've found this blog very useful: https://blog.cloudera.com/spark-on-kubernetes-gang-scheduling-with-yunikorn/

**Comment by ravieze** [comment]
Yes. its gang scheduling. I discovered it late. Also, From spark page I see that external scheduler is not yet available on k8s --so how are you handling this part ?
