### ISSUE TITLE
[discussion][API] Custom SparkPodSpec or v1.PodTemplateSpec

### ISSUE THREAD

**Issue by gaocegege** [kubeflow/spark-operator#693]
Hi, I have a question about why we use a customized SparkPodSpec instead of v1.PodTemplateSpec.

Keeping such a customized pod spec is not friendly to users from my opinion.

I'd appreciate it if anyone could help.

**Comment by liyinan926** [comment]
The reason is two-fold:
1. The operator does not create the driver and executor pods directly. The driver pod is created by the Kubernetes submission client in Spark itself as part of running `spark-submit` and the executor pods are created by the driver. So even if we use `PodTemplateSpec`, there's no way to directly turn that into a `PodSpec` for the driver or executor pod. We still need to use built-in Spark config options and the webhook to customize the driver and executor pods. The value of using `PodTemplateSpec` is not as big as it sounds because of this. This will change, however, with the new pod templating feature in the upcoming Spark 3.0. However, to support Spark 2.4.x and earlier, we plan to keep the webhook and use that uniformly for pod customization in both Spark 2.x and Spark 3.x.
2. Initially we only had a limited set of customizations for the driver and executor pods, so it we decided to use a custom type for the driver and executor pod specs.

I actually think using a custom pod spec type that is smaller/simpler than `PodTemplateSpec` is good for users as they have less stuffs to worry about.

**Comment by gaocegege** [comment]
Gotcha, thanks for the explanation.

> I actually think using a custom pod spec type that is smaller/simpler than PodTemplateSpec is good for users as they have less stuffs to worry about.

I think although it may be simpler, users (like me) is familiar with PodSpec. There are higher learning costs.

**Comment by liyinan926** [comment]
> I think although it may be simpler, users (like me) is familiar with PodSpec. There are higher learning costs.

That's understandable. In the future, when Spark 3.0 becomes mainstream, we may decide to support pod templating and change to use `PodTemplateSpec`, which will unfortunately a breaking change though.

**Comment by gaocegege** [comment]
@liyinan926 Thanks. I think it will make the API more Kubernetes native.

> which will unfortunately a breaking change though.

Maybe we could have a [conversion webhook](https://github.com/kubernetes/enhancements/blob/master/keps/sig-api-machinery/20190425-crd-conversion-webhook.md) for the old API version.

**Comment by liyinan926** [comment]
> Maybe we could have a conversion webhook for the old API version.

Yep, that will work.

**Comment by gaocegege** [comment]
Should we keep the issue open to keep track of the discusstion? I think I can help at that time.

**Comment by liyinan926** [comment]
Yep. Let's keep this open and use it as a channel for discussion. Thanks for being interested in helping out!

**Comment by jasonliu747** [comment]
> That's understandable. In the future, when Spark 3.0 becomes mainstream, we may decide to support pod templating and change to use `PodTemplateSpec`, which will unfortunately a breaking change though.

@liyinan926 Looks like Spark 3.0 has become mainstream, should we consider implementing SparkPodSpec using v1.PodSpec?
