### ISSUE TITLE
SparkApplication CRD Deletion: Driver/Executor Pods not deleted

### ISSUE THREAD

**Issue by akhurana001** [kubeflow/spark-operator#834]
Hi,

We are seeing that on some occasions, the SparkApplication CRD deletion doesn't terminate the pods/other resources created for the App.

My understanding is that the deletion logic is best-effort as we can potentially lose the delete event or run into a transient error while trying to delete pods on CRD deletion. This is rare but at scale, we run into a few cases every week. 

We removed a finalizer based enforcement in https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/pull/339 due to underlying bug with finalizers but that's fixed and I was wondering if we can add this back to make sure we don't run into this pod/resource leakage on CRD deletion. 

@liyinan926 / @kumare3 let me know what your thoughts are on this or if there is a better way to enforce this.  I can also pick this up once we decide on the right solution.

**Comment by akhurana001** [comment]
@liyinan926 any thoughts on this ?

**Comment by liyinan926** [comment]
Why can't you use the webhook to add an `ownerReference` to the driver pod and service?

**Comment by akhurana001** [comment]
> Why can't you use the webhook to add an `ownerReference` to the driver pod and service?

Yes, webhook would work but it seems a little expensive solution since it be invoked for all pods (spark/non-spark) created on the cluster.

 In the past, we have seen perf issues (high create-pod/other api latencies) when using webhooks at scale so was hoping to see if there is an better solution to resolve this.

**Comment by AlexeyRumyantsev** [comment]
It happened to me, if I remove CRD too fast, while spark-submit is still in progress. Then cleanup event processed before driver pod has been created, so it's kept (in Pending state in my case, because we expect spark-operator to set some properties to get it scheduled). I am trying this patch https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/compare/master...AlexeyRumyantsev:spark-on-k8s-operator:cleanup_if_crd_removed_before_completion_spark_submit to see if it helps.
