### ISSUE TITLE
[proposal] Add `nodeName` in SparkPodSpec 

### ISSUE THREAD

**Issue by ringtail** [kubeflow/spark-operator#866]
We run spark on virtual-kubelet (virtual-node with a specific name) and When the `spark.kubernetes.allocation.batch.size` is more than 300(total 4000Pods). Spark resource manager would create extral executors more than settings.  We fond the root cause is that some of the Pods in one batch have not been handled by scheduler. If nodeName added we can skip this stage and gain better performance.

**Comment by Jeffwan** [comment]
> We fond the root cause is that some of the Pods in one batch have not been handled by scheduler

Could you add more details here? Do you mean executors in that batch are created but kubernetes default scheduler does't handle them correctly? I assume you mean objects are already created but not scheduled because scheduler can not handle that scale.  

Seems node selector or node affinity won't meet your needs. I think you need this feature? https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#nodename

From scheduling perspective, I think it's reasonable. In real world examples, all executors share same SparkPodSpec, that means all executors will be scheduled on one node.. That's something unacceptable?

**Comment by ringtail** [comment]
@Jeffwan Yes. if you set `nodeName`,that means the process of scheduling would be skipped. virtual-kubelt(https://github.com/virtual-kubelet/virtual-kubelet) is a virtual-node with unlimited capacity. So we can just set the `nodeName` directly, Because all pod need to be scheduled to the same virtual-node.

**Comment by Jeffwan** [comment]
@ringtail I see. That makes sense. Our serverless solution is a little bit different, we have node for each pod so we can not use this solution. Virtual kubelet should be good.  +1

**Comment by ringtail** [comment]
> @ringtail I see. That makes sense. Our serverless solution is a little bit different, we have node for each pod so we can not use this solution. Virtual kubelet should be good. +1

You mean aws fargate?

**Comment by Jeffwan** [comment]
@ringtail Yes. EKS on Fargate uses different implementation than virtual-kubelet.
